app_rate_limit = "10/seconds"
log_level = "DEBUG"
log_file = ".logs/app.log"

# kalau env production reload akan false otomatis
[server]
host = "0.0.0.0"
port = 8080
workers = 4
debug = true

[[members]]
name = "member1"
ipaddress = "192.168.1.1"
report_url = "http://192.168.1.1/report"
rate_limiter = "10/seconds"
is_allowed = true
description = "sample member 1 and ini di bolehin akses"

[[members]]
name = "member2"
ipaddress = "192.168.1.2"
report_url = "http://192.168.1.2/report"
rate_limiter = "10/seconds"
is_allowed = false
description = "sample member 2 and ini di larang akses"


[[digipos]]
url = "http://10.0.0.3/10003/"
username = "admin"
password = "admin"
retries = 3
time_out = 5

[parser.digipos]
# setup untuk parsing data response dari digipos
