
rate_limit = ""
log_level = ""
log_file = ""

[server]
host = ""
port = ""
workers = ""
debug = ""

# jika members ada lebih dari satu, tambahkan array of table [[members]]
[[members]]
name = ""
ipaddress = ""
report_url = ""
rate_limiter = ""
is_allowed = ""
description = ""

# jika akun digipos ada lebih dari satu, tambahkan array of table
[[digipos]]
url = ""
username = ""
password = ""
retries = ""
time_out = ""

[parser.digipos]
# setup untuk parsing data response dari digipos
