[application]
app_rate_limit = "10/seconds"
log_level = "DEBUG"
log_file = ".logs/app.log"
debug = true

[admin]
username = "admin"
password = "admin"
ip_whitelist = ["127.0.0.1"]

[[members]]
name = "member1"
ipaddress = "192.168.1.1"
report_url = "http://192.168.1.1/report"
rate_limiter = "10/seconds"
is_allowed = true
description = "sample member 1 and ini di bolehin akses"

[[members]]
name = "member2"
ipaddress = "192.168.1.2"
report_url = "http://192.168.1.2/report"
rate_limiter = "10/seconds"
is_allowed = false
description = "sample member 2 and ini di larang akses"


[[digipos]]
username = "admin"
password = "admin"
pin = ""
base_url = "http://10.0.0.3/10003/"
retries = 3
time_out = 5

[parser.digipos]
max_responses = 7000
